### ISSUE TITLE
How to load mu4e in emacs when installed via snap

### ISSUE THREAD

**Issue by grauschnabel** [alexmurray/mu-snap#4]
Hi, I'm new to snap.

I installed emacs 27.1 and mail-utils from snap today, and I wonder if there is a recommended way to load packages from there.

I did `(add-to-list 'load-path "/snap/maildir-utils/331/share/emacs/site-lisp/mu4e/")` in my config, and it loads. But maybe with snap there are other recomended ways to do that.  Please just give me little feedback,

Martin

**Comment by alexmurray** [comment]
Yes this is correct, although you should not list the specific snap revision (331) and instead use `current` - this is a symlink that points to the current revision. This way if the snap gets refreshed to a newer revision it will still work.

**Comment by grauschnabel** [comment]
Thanks, that's what i need to know. :)
