### ISSUE TITLE
Email in Emacs with mu and mu4e for beginners

### ISSUE THREAD

**Issue by Richard-CAID** [alexmurray/mu-snap#5]
I am slowly moving my work into emacs (I use spacemacs). I use it primarily for documents and logs working with Ebib, time clocking, org-capture, and org-agenda. I know I have to move forward into incorporating emails into emacs and then into my .bib files and their notes. However, I am not a programmer but I do learn as I move forward.

Email in emacs/spacemacs with mu and mu4e is overwhelming without a starting point and manuals that are at my level. What I ahve read I need to acquire maildir for mu and mu4e plus mbsync. But that is where there is a disconnect between information that is available currently and what seasoned emace/spacemacs users know from an earlier time.

Can you direct me to information/manuals that non-programmers can understand and learn from to get email up and running in emacs?

**Comment by alexmurray** [comment]
This is not really the right place for such a support request - however, for myself I used the following resources to setup mu4e + mbsync:

https://www.djcbsoftware.nl/code/mu/mu4e/Getting-mail.html#Getting-mail
http://cachestocaches.com/2017/3/complete-guide-email-emacs-using-mu-and-/

Plus the following tutorials all look pretty approachable:

https://f-santos.gitlab.io/2020-04-24-mu4e.html

https://www.reddit.com/r/emacs/comments/bfsck6/mu4e_for_dummies/

Good luck.

**Comment by Richard-CAID** [comment]
Appreciated
