### ISSUE TITLE
Mu using hostname to 

### ISSUE THREAD

**Issue by Richard-CAID** [alexmurray/mu-snap#7]
An interesting issue I came across is Mu4e (Mu) recognising by computer's hostname as my email address (username@hostname) and (1) using my hostname in naming emails and (2)  providing a message that 'user-mail-address' (username@hostname) is not part of mu's addresses; add it with 'mu init -- my-address='  When I attempt to enter my correct email address (mu init --my-address=username@domain), I receive an "error: missing  --maildir parameter and could not determine default (2)" No, I am not able to update and receive emails through Mu4e, but I am working on Mu4e configuration and may have a separate reason for no access to email retrieval through Mu4e. Emails have have received from initializing Mu and Mbsync are what I have received with my hostname tagged on to them.

Help?

**Comment by alexmurray** [comment]
I think these sorts of support requests would be better handled via the mu-discuss mailing list (https://groups.google.com/g/mu-discuss/) or if there are particular issues with mu (which are not specific to the mu snap) then to the mu issue tracker directly (https://github.com/djcb/mu/issues/). Closing this issue as it does not appear to be a specific issue with mu as a snap.
